### ISSUE TITLE
a part of docs makes me puzzle

### ISSUE THREAD

**Issue by teteko233** [CaiJimmy/stack-docs-v1#19]
**问题描述：**
基础 → 开始使用 → 下载主题 中：
如果是第一次使用本主题，建议把 `exampleSite` 文件夹中的 `assets` 和 `config.yaml` 复制到站点目录下。后者是 Hugo 站点的配置文件，已经写入了主题的可配置字段。

**实际情况：**
`asstes` 是 `exampleSite` 的同级文件夹，并不在 `exampleSite` 文件夹内

望修改！

**Comment by CaiJimmy** [comment]
谢谢提醒！

中文文档已经很久都没有更新了（英文文档也是）。由于缺少维护，现在已经下线。未来会专注于更新英文版文档。
